### ISSUE TITLE
Switching is working, however temperature is read as "null"

### ISSUE THREAD

**Issue by darezik** [thunderbird/homebridge-w215#1]
I've pasted the output below, and it'd be great if you could take some time to look at it?
My firmware version is 1.24, and the switching is working. 

error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Values
{ power: true,
  consumption: 0,
  totalConsumption: NaN,
  temperature: 0 }

Amazing work, anyway, this module has been super helpful :)

**Comment by ianmichell** [comment]
Looks like an issue with the library I used. I'll fix it and create a pull request to original author.

**Comment by ianmichell** [comment]
I've added an additional check at that line. Essentially if the value is null then we need to ensure that it returns "ERROR"

I would help if you could elaborate on how often this happens. Is it all the time?

**Comment by darezik** [comment]
I've solved this issue myself. Turns out it is a variant of bikerp/dsp-w215-hnap#2. I corrected them for my local installation(it is hardware version dependent) and now everything is working correctly.

**Comment by thatsnasty** [comment]
I'm having the same problem, @darezik could be more specific in what you corrected and where? I'm a little confused as to what I'm editing exactly.

**Comment by ryanbeaton** [comment]
Hi @thatsnasty what I just did to fix it is edit the soapclient.js file in "/usr/local/lib/node_modules/homebridge-w215/node_modules/hnap/js" (Mac path, yours may be different) to change:
every instance of moduleParameters(2)) to moduleParameters(3)) - there are four instances 
AND
every instance of moduleParameters(3)) to moduleParameters(2)) - there are two.

great success! :)
Credit to info in https://github.com/bikerp/dsp-w215-hnap/issues/2

**Comment by mogensboegh** [comment]
Hi
Thank you a lot
I will implement the modifications and I look forward to the seeing the
result

Best regards

Med venlig hilsen
Mogens Bøgh Mortensen
Mosevej 7
Hedeskov
8410 Rønde
Mob 22246731
Mail mogensboegh@gmail.com

2018-04-28 16:42 GMT+02:00 Ryan Beaton <notifications@github.com>:
