### ISSUE TITLE
Added to Home, but no readings/control

### ISSUE THREAD

**Issue by TimCombridge** [thunderbird/homebridge-w215#4]
Hi,
Thanks for putting this together!

I've been able to get the switches in my Home app, but that's about it.
I can see all three switches in the app, as well as the temperature icon, but I cannot control the switches or read them from Home. 
When I press the switch on a button, the Homebridge shows this:
0
OK
1
OK
0
OK
1
OK
(As if it is recognising that I am pressing these buttons, but not actually changing it. When I restart Homebridge it seems to pick up the status of the switches correctly (ie, if my Study Heater is on it will be able to see this, but not change it)

I am receiving the following error when it appears to be trying to get the temperature value.

error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Values
{ power: true,
  consumption: 0,
  totalConsumption: NaN,
  temperature: 0 }
Values
{ power: true,
  consumption: 0,
  totalConsumption: NaN,
  temperature: 0 }
Values
{ power: true,
  consumption: 0,
  totalConsumption: NaN,
  temperature: 0 }
Values
{ power: true,
  consumption: 0,
  totalConsumption: NaN,
  temperature: 0 }
error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
Values
{ power: true,
  consumption: 0,
  totalConsumption: NaN,
  temperature: 0 }
Values
{ power: true,
  consumption: 0,
  totalConsumption: NaN,
  temperature: 0 }

Please also find my config.json

{
    "bridge": {
        "name": "Homebridge",
        "username": "xx:xx:xx:xx:xx:xx",
        "port": xxxxx,
        "pin": "xxx-xx-xxx"
    },

    "description": "This is an example configuration file with one fake accessory and one fake platform. You can use this as a template for creating your own configuration file containing devices you actually own.",

    "accessories": [
        {
                "accessory": "w215",
                "name": "Study Heater",
                "host": "xxx.xxx.x.xx",
                "username": "admin",
                "password": "xxxxxx"
},

{
                "accessory": "w215",
                "name": "Bedroom Heater",
                "host": "xxx.xxx.x.xx",
                "username": "admin",
                "password": "xxxxxx"
},

{
                "accessory": "w215",
                "name": "Bedroom Steamer",
                "host": "xxx.xxx.x.xx",
                "username": "admin",
                "password": "xxxxxx"
}
    ]
    
    }

Please let me know if I can provide any further information to assist.

**Comment by TimCombridge** [comment]
I just realised that this is already a recognised issue, and that in fact all three buttons are controlling the same switch. I’ll refer to that thread. Thanks!
