### ISSUE TITLE
Multiple plug error

### ISSUE THREAD

**Issue by spaceman1212** [thunderbird/homebridge-w215#6]
I am getting the following error and all plugs are not working when i am using multiple plugs.

One plug works fine, though multiple has issue. The window still shows the button going 0 or 1 for on or off.

Error:

error: TypeError: Cannot read property 'nodeValue' of null
    at readResponseValue (/usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:248:40)
    at /usr/lib/node_modules/homebridge-w215/node_modules/hnap/js/soapclient.js:81:16
    at tryCallOne (/usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/homebridge-w215/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/homebridge-w215/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by ianmichell** [comment]
What version of the  plugin are you using?

**Comment by spaceman1212** [comment]
w215 with firmware 1.25

**Comment by ianmichell** [comment]
No, the plugin I wrote.

**Comment by spaceman1212** [comment]
is this the version: Loaded plugin: homebridge-w215
homebridge API version: 2.2

**Comment by spaceman1212** [comment]
worked out the issue. I was on version 0.2 now on v 0.6 and working. Not sure why it installed the old version.
